global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'simulation'
    static_configs:
      - targets: ['simulation-1:8000']

  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus-standalone:9091']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']