---
# Security Configuration for Self-Organizing AI System

ssl:
  enabled: true
  protocols:
    min_version: TLSv1_2
    max_version: TLSv1_3
  cipher_suites:
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES128-GCM-SHA256
  certificate:
    validity_days: 365
    key_size: 2048
    country: US
    organization: Development
    common_name: localhost

session:
  timeout: 7200  # seconds
  ticket_lifetime: 300  # seconds
  cache_size: 1024

security_headers:
  strict_transport_security:
    enabled: true
    max_age: 31536000
    include_subdomains: true
  content_security_policy:
    enabled: true
    default_src: "'self'"
    script_src: "'self'"
    style_src: "'self'"
  x_frame_options: DENY
  x_content_type_options: nosniff
  x_xss_protection: "1; mode=block"
  referrer_policy: strict-origin-when-cross-origin

cors:
  development:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
  production:
    enabled: true
    allowed_origins: ["https://localhost", "https://127.0.0.1"]
    allowed_methods: ["GET", "POST"]
    allowed_headers: ["Authorization", "Content-Type"]

rate_limiting:
  enabled: true
  max_requests: 100
  window_seconds: 60
  strategy: sliding_window

monitoring:
  security_events:
    enabled: true
    log_level: INFO
    metrics_enabled: true
  failed_attempts:
    log_threshold: 3
    ban_threshold: 10
    ban_duration: 3600  # seconds

authentication:
  api_key:
    enabled: true
    key_rotation_days: 90
  jwt:
    enabled: false
    algorithm: HS256
    expiration_minutes: 60
    refresh_enabled: true
    refresh_expiration_days: 7